import "dotenv/config";

import prisma from "@/shared/db";

// 模拟当前用户在数据库中的 ID
const OWNER_ID = "cmrjdu92f0001099de7h2zu5p";

// 规约生成数量
const RULE_COUNT = 50;

// @ 规约模板，按业务主题分组
const ruleTemplates = [
	{
		name: "使用函数组件",
		content: [
			"# React 组件规范",
			"",
			"## 函数组件",
			"",
			"所有新组件必须使用函数声明，禁止使用 class 组件。",
			"",
			"```tsx",
			"// ✅ 正确",
			"function MyComponent({ name }: Props): JSX.Element {",
			"  return <div>{name}</div>;",
			"}",
			"",
			"// ❌ 错误",
			"class MyComponent extends React.Component {",
			"  render() {",
			"    return <div>{this.props.name}</div>;",
			"  }",
			"}",
			"```",
			"",
			"## Props 类型",
			"",
			"Props 必须显式声明类型，使用 interface 而非 type。",
			"",
			"```tsx",
			"interface Props {",
			"  name: string;",
			"  onClick: () => void;",
			"}",
			"```",
		].join("\n"),
	},
	{
		name: "避免 any 类型",
		content: [
			"# TypeScript 类型规范",
			"",
			"## 禁止 any",
			"",
			"所有代码禁止使用 `any` 类型，必须明确指定类型。",
			"",
			"```typescript",
			"// ❌ 错误",
			"const data: any = fetchData();",
			"",
			"// ✅ 正确",
			"const data: UserData = fetchData();",
			"```",
			"",
			"## 类型断言",
			"",
			"避免使用 `as` 进行类型断言，优先使用类型守卫。",
			"",
			"```typescript",
			"// ❌ 避免",
			"const value = data as string;",
			"",
			"// ✅ 推荐",
			"if (typeof data === 'string') {",
			"  const value = data;",
			"}",
			"```",
		].join("\n"),
	},
	{
		name: "错误必须显式处理",
		content: [
			"# 错误处理规范",
			"",
			"## 显式处理",
			"",
			"所有错误必须显式处理，禁止忽略错误。",
			"",
			"```typescript",
			"// ❌ 错误：忽略错误",
			"fetchData();",
			"",
			"// ✅ 正确：显式处理",
			"try {",
			"  await fetchData();",
			"} catch (error) {",
			"  toast.error('获取数据失败');",
			"}",
			"```",
			"",
			"## 错误类型",
			"",
			"使用项目统一的错误类型，不要直接抛出原生 Error。",
			"",
			"```typescript",
			"import { AiSpecError } from '@/server/errors/http-error';",
			"",
			"throw new AiSpecError({",
			"  code: ErrorCode.NOT_FOUND,",
			"  message: '资源不存在',",
			"});",
			"```",
		].join("\n"),
	},
	{
		name: "使用 Tailwind CSS",
		content: [
			"# 样式规范",
			"",
			"## Tailwind CSS",
			"",
			"优先使用 Tailwind CSS 工具类，避免自定义 CSS。",
			"",
			"```tsx",
			"// ✅ 正确",
			"<div className=\"flex items-center gap-2 p-4\">",
			"  <span className=\"text-sm font-medium\">标题</span>",
			"</div>",
			"",
			"// ❌ 错误",
			"<div style={{ display: 'flex', padding: '16px' }}>",
			"  <span style={{ fontSize: '14px' }}>标题</span>",
			"</div>",
			"```",
			"",
			"## 颜色变量",
			"",
			"使用 CSS 变量引用主题色，不要硬编码颜色值。",
			"",
			"```tsx",
			"// ✅ 正确",
			"<div className=\"text-primary bg-background\">",
			"",
			"// ❌ 错误",
			"<div className=\"text-blue-500 bg-white\">",
			"```",
		].join("\n"),
	},
	{
		name: "Git 提交规范",
		content: [
			"# Git 提交规范",
			"",
			"## 提交信息格式",
			"",
			"使用 Conventional Commits 格式：",
			"",
			"```",
			"<type>(<scope>): <subject>",
			"",
			"[optional body]",
			"",
			"[optional footer]",
			"```",
			"",
			"## 类型说明",
			"",
			"- `feat`: 新功能",
			"- `fix`: 修复 bug",
			"- `docs`: 文档更新",
			"- `style`: 代码格式（不影响功能）",
			"- `refactor`: 重构",
			"- `test`: 测试相关",
			"- `chore`: 构建/工具相关",
			"",
			"## 示例",
			"",
			"```",
			"feat(auth): 添加 Google OAuth 登录",
			"",
			"fix(api): 修复用户列表分页错误",
			"",
			"docs: 更新 README 安装说明",
			"```",
		].join("\n"),
	},
	{
		name: "API 接口规范",
		content: [
			"# API 接口规范",
			"",
			"## RESTful 设计",
			"",
			"接口遵循 RESTful 设计原则：",
			"",
			"- GET：获取资源",
			"- POST：创建资源",
			"- PUT/PATCH：更新资源",
			"- DELETE：删除资源",
			"",
			"## 响应格式",
			"",
			"统一返回 JSON 格式：",
			"",
			"```json",
			"{",
			"  \"data\": {},",
			"  \"error\": {",
			"    \"message\": \"错误信息\",",
			"    \"code\": \"ERROR_CODE\"",
			"  }",
			"}",
			"```",
			"",
			"## 状态码",
			"",
			"- 200：成功",
			"- 201：创建成功",
			"- 400：请求参数错误",
			"- 401：未授权",
			"- 403：禁止访问",
			"- 404：资源不存在",
			"- 500：服务器内部错误",
		].join("\n"),
	},
	{
		name: "数据库查询优化",
		content: [
			"# 数据库查询优化",
			"",
			"## 索引使用",
			"",
			"为高频查询字段添加索引：",
			"",
			"```prisma",
			"@@index([ownerId])",
			"@@index([createdAt])",
			"```",
			"",
			"## 分页查询",
			"",
			"使用 offset 分页，避免一次性加载大量数据：",
			"",
			"```typescript",
			"const data = await prisma.rule.findMany({",
			"  take: 30,",
			"  skip: offset,",
			"  orderBy: { updatedAt: 'desc' },",
			"});",
			"```",
			"",
			"## 选择字段",
			"",
			"只查询需要的字段，减少数据传输：",
			"",
			"```typescript",
			"const data = await prisma.rule.findMany({",
			"  select: {",
			"    id: true,",
			"    name: true,",
			"    content: true,",
			"  },",
			"});",
			"```",
		].join("\n"),
	},
	{
		name: "测试编写规范",
		content: [
			"# 测试编写规范",
			"",
			"## 测试覆盖",
			"",
			"核心功能必须有测试覆盖：",
			"",
			"- 正常流程测试",
			"- 异常流程测试",
			"- 边界条件测试",
			"",
			"## 测试结构",
			"",
			"使用 AAA 模式（Arrange-Act-Assert）：",
			"",
			"```typescript",
			"test('should create rule', async () => {",
			"  // Arrange",
			"  const input = { name: 'test', content: 'content' };",
			"",
			"  // Act",
			"  const result = await createRule(input);",
			"",
			"  // Assert",
			"  expect(result.name).toBe('test');",
			"});",
			"```",
			"",
			"## 测试命名",
			"",
			"测试名称应清晰描述测试内容：",
			"",
			"```typescript",
			"// ✅ 正确",
			"test('should return 404 when rule not found')",
			"",
			"// ❌ 错误",
			"test('test1')",
			"```",
		].join("\n"),
	},
	{
		name: "性能优化指南",
		content: [
			"# 性能优化指南",
			"",
			"## React 性能",
			"",
			"### 避免不必要的重渲染",
			"",
			"```tsx",
			"// ✅ 使用 memo 避免重渲染",
			"const MemoizedComponent = React.memo(Component);",
			"",
			"// ✅ 使用 useMemo 缓存计算结果",
			"const expensiveResult = useMemo(() => compute(data), [data]);",
			"",
			"// ✅ 使用 useCallback 缓存函数",
			"const handleClick = useCallback(() => {",
			"  // ...",
			"}, []);",
			"```",
			"",
			"## 数据加载",
			"",
			"使用 SWR 进行数据缓存和自动重新验证：",
			"",
			"```tsx",
			"const { data, error } = useSWR('/api/rules', fetcher);",
			"```",
			"",
			"## 图片优化",
			"",
			"使用 Next.js Image 组件自动优化图片：",
			"",
			"```tsx",
			"import Image from 'next/image';",
			"",
			"<Image",
			"  src=\"/photo.jpg\"",
			"  alt=\"描述\"",
			"  width={500}",
			"  height={300}",
			"/>",
			"```",
		].join("\n"),
	},
	{
		name: "安全编码规范",
		content: [
			"# 安全编码规范",
			"",
			"## 输入验证",
			"",
			"所有用户输入必须验证：",
			"",
			"```typescript",
			"import { z } from 'zod';",
			"",
			"const schema = z.object({",
			"  name: z.string().min(1).max(100),",
			"  email: z.string().email(),",
			"});",
			"",
			"const result = schema.safeParse(input);",
			"if (!result.success) {",
			"  throw new Error('输入验证失败');",
			"}",
			"```",
			"",
			"## SQL 注入防护",
			"",
			"使用参数化查询，禁止拼接 SQL：",
			"",
			"```typescript",
			"// ✅ 正确：使用 Prisma",
			"await prisma.user.findMany({",
			"  where: { email: userInput },",
			"});",
			"",
			"// ❌ 错误：拼接 SQL",
			"await prisma.$queryRaw(`SELECT * FROM users WHERE email = '${userInput}'`);",
			"```",
			"",
			"## XSS 防护",
			"",
			"渲染用户内容时进行转义：",
			"",
			"```tsx",
			"// ✅ 正确：React 自动转义",
			"<div>{userContent}</div>",
			"",
			"// ❌ 错误：直接渲染 HTML",
			"<div dangerouslySetInnerHTML={{ __html: userContent }} />",
			"```",
		].join("\n"),
	},
];

// 返回 [min, max] 闭区间内的随机整数
const randomInt = (min: number, max: number): number =>
	Math.floor(Math.random() * (max - min + 1)) + min;

// > 生成单条规约数据
const generateRule = (
	index: number,
	spaceId: string,
): {
	name: string;
	content: string;
	ownerId: string;
	spaceId: string;
	folderId: null;
	createdAt: Date;
	updatedAt: Date;
} => {
	const template = ruleTemplates[index % ruleTemplates.length];
	const serial = Math.floor(index / ruleTemplates.length) + 1;
	const baseDate = new Date(2026, 6, 10, 9, 0, 0, 0);
	const createdAt = new Date(baseDate.getTime() + index * 7 * 60 * 1000);
	const updatedAt = new Date(createdAt.getTime() + randomInt(0, 60) * 1000);

	return {
		name: `${template.name}${serial > 1 ? ` v${serial}` : ""}`,
		content: template.content,
		ownerId: OWNER_ID,
		spaceId,
		folderId: null,
		createdAt,
		updatedAt,
	};
};

// 主流程：先清空当前用户的规约，再写入新数据
const main = async (): Promise<void> => {
	// 获取或创建用户的个人规则空间
	let space = await prisma.ruleSpace.findFirst({
		where: { ownerId: OWNER_ID, teamId: null },
		select: { id: true },
	});

	if (!space) {
		space = await prisma.ruleSpace.create({
			data: {
				name: "我的规约",
				icon: "rules",
				ownerId: OWNER_ID,
				teamId: null,
			},
			select: { id: true },
		});
		console.log("✓ 创建个人规则空间");
	}

	// 清空当前用户的规约
	const deleted = await prisma.rule.deleteMany({ where: { ownerId: OWNER_ID } });

	// 生成规约数据
	const rules = Array.from({ length: RULE_COUNT }, (_, index) =>
		generateRule(index, space.id),
	);

	// 批量写入规约
	await prisma.rule.createMany({ data: rules });

	console.log(`已清理 ${deleted.count} 条旧规约`);
	console.log(`✓ 写入 ${RULE_COUNT} 条规约`);
};

main()
	.catch((error: unknown) => {
		console.error("填充规约失败:", error);
		process.exit(1);
	})
	.finally(async () => {
		await prisma.$disconnect();
	});
