allowBuilds:
  "@prisma/engines": true
  dprint: true
  esbuild: true
  msgpackr-extract: false
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - lucide-react@1.23.0
