allowBuilds:
  "@prisma/engines": true
  dprint: true
  esbuild: true
  msgpackr-extract: false
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - lucide-react@1.23.0
  - '@orpc/client@2.0.0-beta.23'
  - '@orpc/contract@2.0.0-beta.23'
  - '@orpc/json-schema@2.0.0-beta.23'
  - '@orpc/openapi@2.0.0-beta.23'
  - '@orpc/server@2.0.0-beta.23'
  - '@orpc/shared@2.0.0-beta.23'
  - '@orpc/tanstack-query@2.0.0-beta.23'
  - '@orpc/zod@2.0.0-beta.23'
  - '@standardserver/core@0.6.0'
  - '@standardserver/fetch@0.6.0'
  - '@standardserver/node@0.6.0'
  - '@standardserver/peer@0.6.0'
