// # Discover skills 前端可见 license 白名单

/**
 * 广场前端可见的 license 白名单（SPDX id）。
 *
 * 口径：免费目录站「元数据索引」——可展示 name / description，并附 license 与来源回链；
 * 不表示用户可把 SKILL 全文闭源商用拷贝进自有项目。抓取入库仍可保留更广协议，仅读接口按此过滤。
 *
 * 组成：
 * 1. 宽松协议（Blue Oak Bronze+ / GitHub 高频优先，再补常见变体）
 * 2. 内容向 CC-BY / CC0 / CC-BY-SA（不含 NC / ND）
 * 3. 弱/强 copyleft（MPL/EPL/LGPL/GPL/AGPL 等；目录索引场景可展示）
 * 另：license 为空（无协议）由查询侧单独放行，同样展示 description +「无协议」标记 + 回链。
 *
 * 明确不进：CC-BY-NC*、BUSL、SSPL、Elastic、FSL 等非商用或源可用限制协议。
 */
export const DISCOVER_FRONTEND_LICENSE_ALLOWLIST = [
	// @ 1a GitHub 高频宽松
	"0BSD",
	"AFL-3.0",
	"Apache-1.0",
	"Apache-1.1",
	"Apache-2.0",
	"Artistic-2.0",
	"BlueOak-1.0.0",
	"BSD-1-Clause",
	"BSD-2-Clause",
	"BSD-2-Clause-Patent",
	"BSD-3-Clause",
	"BSD-3-Clause-Clear",
	"BSD-4-Clause",
	"BSL-1.0",
	"CC0-1.0",
	"ECL-2.0",
	"ISC",
	"MIT",
	"MIT-0",
	"MS-PL",
	"MulanPSL-1.0",
	"MulanPSL-2.0",
	"NCSA",
	"PHP-3.0",
	"PHP-3.01",
	"PostgreSQL",
	"PSF-2.0",
	"Python-2.0",
	"Ruby",
	"Unlicense",
	"UPL-1.0",
	"WTFPL",
	"Zlib",

	// @ 1b 宽松常见变体（Blue Oak Bronze+ / 生态常见）
	"AFL-1.1",
	"AFL-1.2",
	"AFL-2.0",
	"AFL-2.1",
	"BSD-2-Clause-Views",
	"BSD-3-Clause-Attribution",
	"BSD-3-Clause-LBNL",
	"BSD-3-Clause-Open-MPI",
	"BSD-4-Clause-UC",
	"curl",
	"ECL-1.0",
	"EFL-2.0",
	"Fair",
	"FSFAP",
	"FSFUL",
	"FSFULLR",
	"FTL",
	"GLWTPL",
	"HPND",
	"HTMLTIDY",
	"ICU",
	"IJG",
	"ImageMagick",
	"Intel",
	"Jam",
	"Libpng",
	"libpng-2.0",
	"Linux-OpenIB",
	"MirOS",
	"MIT-Modern-Variant",
	"Multics",
	"Naumen",
	"NTP",
	"OLDAP-2.8",
	"OpenSSL",
	"SMLNJ",
	"TCL",
	"Unicode-3.0",
	"Unicode-DFS-2015",
	"Unicode-DFS-2016",
	"W3C",
	"W3C-20150513",
	"X11",
	"Xnet",
	"ZPL-1.1",
	"ZPL-2.0",
	"ZPL-2.1",
	"blessing",
	"Beerware",

	// @ 2 内容向 CC（可商用展示；不含 NC/ND）
	"CC-BY-1.0",
	"CC-BY-2.0",
	"CC-BY-2.5",
	"CC-BY-3.0",
	"CC-BY-3.0-US",
	"CC-BY-4.0",
	"CC-BY-SA-2.0",
	"CC-BY-SA-2.5",
	"CC-BY-SA-3.0",
	"CC-BY-SA-4.0",
	"CC-PDDC",

	// @ 3 弱 copyleft（目录可展示 name/description + 回链）
	"MPL-1.1",
	"MPL-2.0",
	"MPL-2.0-no-copyleft-exception",
	"EPL-1.0",
	"EPL-2.0",
	"CDDL-1.0",
	"CDDL-1.1",
	"CPL-1.0",
	"IPL-1.0",
	"MS-RL",
	"EUPL-1.1",
	"EUPL-1.2",
	"LGPL-2.0",
	"LGPL-2.0-only",
	"LGPL-2.0-or-later",
	"LGPL-2.1",
	"LGPL-2.1-only",
	"LGPL-2.1-or-later",
	"LGPL-3.0",
	"LGPL-3.0-only",
	"LGPL-3.0-or-later",

	// @ 4 强 copyleft（同上；GitHub 旧 id 与 SPDX only/or-later 都收录）
	"GPL-2.0",
	"GPL-2.0-only",
	"GPL-2.0-or-later",
	"GPL-3.0",
	"GPL-3.0-only",
	"GPL-3.0-or-later",
	"AGPL-3.0",
	"AGPL-3.0-only",
	"AGPL-3.0-or-later",
	"OSL-2.1",
	"OSL-3.0",
	"CECILL-2.1",
] as const;
