// # 规则业务模板：12 个贴近真实规约的主题，每条含 markdown 正文 + 代码块

export type RuleTemplate = {
	name: string;
	content: string;
};

// @ 业务模板：覆盖常见编码规范主题，正文形态贴近真实规约
export const ruleTemplates: RuleTemplate[] = [
	{
		name: "使用函数组件",
		content: [
			"# React 组件规范",
			"",
			"## 函数组件",
			"",
			"所有新组件必须使用函数声明，禁止使用 class 组件。",
			"",
			"```tsx",
			"// ✅ 正确",
			"function MyComponent({ name }: Props): JSX.Element {",
			"  return <div>{name}</div>;",
			"}",
			"",
			"// ❌ 错误",
			"class MyComponent extends React.Component {",
			"  render() {",
			"    return <div>{this.props.name}</div>;",
			"  }",
			"}",
			"```",
			"",
			"## Props 类型",
			"",
			"Props 必须显式声明类型，使用 interface 而非 type。",
			"",
			"```tsx",
			"interface Props {",
			"  name: string;",
			"  onClick: () => void;",
			"}",
			"```",
		].join("\n"),
	},
	{
		name: "避免 any 类型",
		content: [
			"# TypeScript 类型规范",
			"",
			"## 禁止 any",
			"",
			"所有代码禁止使用 `any` 类型，必须明确指定类型。",
			"",
			"```typescript",
			"// ❌ 错误",
			"const data: any = fetchData();",
			"",
			"// ✅ 正确",
			"const data: UserData = fetchData();",
			"```",
			"",
			"## 类型断言",
			"",
			"避免使用 `as` 进行类型断言，优先使用类型守卫。",
			"",
			"```typescript",
			"// ❌ 避免",
			"const value = data as string;",
			"",
			"// ✅ 推荐",
			"if (typeof data === 'string') {",
			"  const value = data;",
			"}",
			"```",
		].join("\n"),
	},
	{
		name: "错误必须显式处理",
		content: [
			"# 错误处理规范",
			"",
			"## 显式处理",
			"",
			"所有错误必须显式处理，禁止忽略错误。",
			"",
			"```typescript",
			"// ❌ 错误：忽略错误",
			"fetchData();",
			"",
			"// ✅ 正确：显式处理",
			"try {",
			"  await fetchData();",
			"} catch (error) {",
			"  toast.error('获取数据失败');",
			"}",
			"```",
			"",
			"## 错误类型",
			"",
			"使用项目统一的错误类型，不要直接抛出原生 Error。",
			"",
			"```typescript",
			"throw new AiSpecError({",
			"  code: ErrorCode.NOT_FOUND,",
			"  message: '资源不存在',",
			"});",
			"```",
		].join("\n"),
	},
	{
		name: "使用 Tailwind CSS",
		content: [
			"# 样式规范",
			"",
			"## Tailwind CSS",
			"",
			"优先使用 Tailwind CSS 工具类，避免自定义 CSS。",
			"",
			"```tsx",
			"// ✅ 正确",
			'<div className="flex items-center gap-2 p-4">',
			"</div>",
			"",
			"// ❌ 错误",
			"<div style={{ display: 'flex', padding: '16px' }}>",
			"</div>",
			"```",
			"",
			"## 颜色变量",
			"",
			"使用 CSS 变量引用主题色，不要硬编码颜色值。",
			"",
			"```tsx",
			"// ✅ 正确",
			'<div className="text-primary bg-background">',
			"```",
		].join("\n"),
	},
	{
		name: "Git 提交规范",
		content: [
			"# Git 提交规范",
			"",
			"## 提交信息格式",
			"",
			"使用 Conventional Commits 格式：",
			"",
			"```",
			"<type>(<scope>): <subject>",
			"",
			"[optional body]",
			"```",
			"",
			"## 类型说明",
			"",
			"- `feat`: 新功能",
			"- `fix`: 修复 bug",
			"- `docs`: 文档更新",
			"- `refactor`: 重构",
			"- `test`: 测试相关",
			"- `chore`: 构建/工具相关",
		].join("\n"),
	},
	{
		name: "API 接口规范",
		content: [
			"# API 接口规范",
			"",
			"## RESTful 设计",
			"",
			"接口遵循 RESTful 设计原则：",
			"",
			"- GET：获取资源",
			"- POST：创建资源",
			"- PUT：更新资源",
			"- DELETE：删除资源",
			"",
			"## 响应格式",
			"",
			"```json",
			"{",
			'  "data": {},',
			'  "error": { "message": "错误信息", "code": "ERROR_CODE" }',
			"}",
			"```",
		].join("\n"),
	},
	{
		name: "数据库查询优化",
		content: [
			"# 数据库查询优化",
			"",
			"## 索引使用",
			"",
			"为高频查询字段添加索引：",
			"",
			"```prisma",
			"@@index([ownerId])",
			"@@index([createdAt])",
			"```",
			"",
			"## 分页查询",
			"",
			"```typescript",
			"const data = await prisma.rule.findMany({",
			"  take: 30,",
			"  skip: offset,",
			"  orderBy: { updatedAt: 'desc' },",
			"});",
			"```",
		].join("\n"),
	},
	{
		name: "测试编写规范",
		content: [
			"# 测试编写规范",
			"",
			"## 测试覆盖",
			"",
			"核心功能必须有测试覆盖：",
			"",
			"- 正常流程测试",
			"- 异常流程测试",
			"- 边界条件测试",
			"",
			"## AAA 模式",
			"",
			"```typescript",
			"test('should create rule', async () => {",
			"  // Arrange",
			"  const input = { name: 'test', content: 'content' };",
			"  // Act",
			"  const result = await createRule(input);",
			"  // Assert",
			"  expect(result.name).toBe('test');",
			"});",
			"```",
		].join("\n"),
	},
	{
		name: "性能优化指南",
		content: [
			"# 性能优化指南",
			"",
			"## React 性能",
			"",
			"### 避免不必要的重渲染",
			"",
			"```tsx",
			"// 使用 memo 避免重渲染",
			"const MemoizedComponent = React.memo(Component);",
			"",
			"// 使用 useMemo 缓存计算结果",
			"const expensiveResult = useMemo(() => compute(data), [data]);",
			"```",
			"",
			"## 图片优化",
			"",
			"使用 Next.js Image 组件自动优化图片：",
			"",
			"```tsx",
			"import Image from 'next/image';",
			'<Image src="/photo.jpg" alt="描述" width={500} height={300} />',
			"```",
		].join("\n"),
	},
	{
		name: "安全编码规范",
		content: [
			"# 安全编码规范",
			"",
			"## 输入验证",
			"",
			"所有用户输入必须验证：",
			"",
			"```typescript",
			"import { z } from 'zod';",
			"const schema = z.object({",
			"  name: z.string().min(1).max(100),",
			"  email: z.string().email(),",
			"});",
			"```",
			"",
			"## XSS 防护",
			"",
			"渲染用户内容时进行转义：",
			"",
			"```tsx",
			"// ✅ 正确：React 自动转义",
			"<div>{userContent}</div>",
			"```",
		].join("\n"),
	},
	{
		name: "命名规范",
		content: [
			"# 命名规范",
			"",
			"## 通用规则",
			"",
			"- 类、类型、组件用 PascalCase",
			"- 函数、变量用 camelCase",
			"- 文件名用 kebab-case",
			"- 常量用 UPPER_SNAKE_CASE",
			"",
			"## 示例",
			"",
			"```typescript",
			"// ✅ 类型",
			"interface UserProfile { ... }",
			"",
			"// ✅ 函数",
			"const fetchUserData = async () => { ... };",
			"",
			"// ✅ 常量",
			"const MAX_RETRY_COUNT = 3;",
			"```",
		].join("\n"),
	},
	{
		name: "注释规范",
		content: [
			"# 注释规范",
			"",
			"## 何时写注释",
			"",
			"- 新增/重写的函数、组件、类、导出常量上方加简短中文注释",
			"- 注释说明业务目的，不复述语法",
			"- 不写「为什么这么改」，理由属于 commit message",
			"",
			"## 层次标记",
			"",
			"- `#` 文件级标题",
			"- `@` 章节分组标题",
			"- `>` 重点说明",
			"- `!` 警示",
			"- `?` 疑问",
			"",
			"```typescript",
			"// # 用户服务：处理用户增删改查",
			"// > 软删除策略：deleted_at 标记而非物理删除",
			"```",
		].join("\n"),
	},
];

// @ 边缘模板：压测列表预览截断、代码高亮、特殊字符转义、超长渲染
export type EdgeRuleTemplate = {
	name: string;
	content: string;
	edgeTag: string;
};

// > 边缘规则：每个针对一个具体渲染/存储压力点
export const edgeRuleTemplates: EdgeRuleTemplate[] = [
	{
		// 超长名称：正好 64 字符，测列表名称列截断
		name: (
			"前端工程化最佳实践与性能优化完全指南涵盖模块化构建打包代码分割懒加载按需加载的进阶方案" +
			"一二三四五六七八九十一二三四五六七八九十一"
		).slice(0, 64),
		content:
			"# 超长名称测试\n\n本条规约的名称正好 64 字符上限，用于验证列表名称列的 `truncate` 是否生效。",
		edgeTag: "longName",
	},
	{
		// 纯代码无说明：测代码高亮在零上下文时的渲染
		name: "纯代码无文字说明",
		content:
			"```typescript\nexport const debounce = <T extends (...args: never[]) => void>(fn: T, delay = 300) => {\n  let timer: ReturnType<typeof setTimeout>;\n  return (...args: Parameters<T>) => {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn(...args), delay);\n  };\n};\n```",
		edgeTag: "pureCode",
	},
	{
		// 特殊字符：含 emoji、HTML 实体、引号、反斜杠
		name: "特殊字符与 Emoji",
		content:
			"# 特殊字符测试\n\n含 Emoji：🎉🚀✅❌💡\n\n含 HTML 实体：&lt;script&gt;alert(1)&lt;/script&gt;\n\n含引号与反斜杠：\"双引号\" '单引号' C:\\\\Users\\\\path",
		edgeTag: "specialChar",
	},
	{
		// 表格语法：测 GFM 表格渲染
		name: "Markdown 表格语法",
		content:
			"# 规则对照表\n\n| 规则 | 正确 | 错误 |\n|------|------|------|\n| 组件 | 函数式 | class |\n| 类型 | 显式 | any |",
		edgeTag: "table",
	},
	{
		// 连续空行：测渲染时空白折叠
		name: "连续空行测试",
		content: `# 连续空行\n\n第一段。\n${"\n".repeat(15)}中间隔了大量空行。\n${"\n".repeat(10)}最后一段。`,
		edgeTag: "blankLines",
	},
	{
		// 极短正文：只有一个标题
		name: "只有一个标题",
		content: "# 极简",
		edgeTag: "minimal",
	},
	{
		// 超长单行代码：测横向滚动
		name: "超长单行代码",
		content:
			"# 超长单行代码\n\n```typescript\nconst x = fn(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20);\n```",
		edgeTag: "longLine",
	},
	{
		// 嵌套代码块：测 markdown 围栏匹配
		name: "嵌套代码块围栏",
		content:
			"# 嵌套代码块\n\n外层四个反引号，内层三个：\n\n````markdown\n```typescript\nconst x = 1;\n```\n````",
		edgeTag: "nestedCode",
	},
	{
		// 中英日韩混排
		name: "中英日韩混排文本",
		content:
			"# 多语言混排\n\n中文 English 日本語 한국어 Mixed Text 12345\n\n代码中混排：`变量名 name 変数 名前 변수 이름`",
		edgeTag: "mixedLang",
	},
	{
		// 超长单段正文（非超长正文系列，中等长度压测预览截断）
		name: "超长单段正文",
		content: `# 超长正文压测\n\n${"这是一段用于压测预览截断与正文渲染的超长文本，重复填充以观察 UI 表现。".repeat(30)}`,
		edgeTag: "longParagraph",
	},
];
