// # 领域空间图标清单：新建空间时可选的图标，DB 里存 key，渲染时映射回组件
//
// 从 @tabler/icons-react 命名导入精选图标（tree-shaking 生效，仅打包这些，不引入全量 6k）；
// 按领域分类，key 用 kebab 命名；保留原有 8 个 key 不变，保证历史数据兼容。

import {
	IconAbc,
	IconArchive,
	IconAtom,
	IconAward,
	IconBell,
	IconBinary,
	IconBolt,
	IconBook,
	IconBook2,
	IconBookmark,
	IconBooks,
	IconBox,
	IconBrain,
	IconBrandOpenai,
	IconBrush,
	IconBug,
	IconBuilding,
	IconBuildingStore,
	IconBuildingWarehouse,
	IconBulb,
	IconCalendar,
	IconCamera,
	IconCertificate,
	IconCertificate2,
	IconChartBar,
	IconChartLine,
	IconChecklist,
	IconCircleCheck,
	IconClipboard,
	IconClipboardList,
	IconClock,
	IconCloud,
	IconCode,
	IconCoffee,
	IconCoin,
	IconColorSwatch,
	IconCpu,
	IconCube,
	IconDatabase,
	IconDeviceDesktop,
	IconEye,
	IconFileText,
	IconFlag,
	IconFlame,
	IconFolder,
	IconGift,
	IconGitBranch,
	IconGlobe,
	IconHash,
	IconHeart,
	IconHexagonLetterA,
	IconHierarchy,
	IconHome,
	IconKey,
	IconLayoutGrid,
	IconLink,
	IconListCheck,
	IconListDetails,
	IconLock,
	IconMail,
	IconMap,
	IconMessage,
	IconMessage2,
	IconMicrophone,
	IconMovie,
	IconMug,
	IconMusic,
	IconNotebook,
	IconNotes,
	IconPalette,
	IconPaletteOff,
	IconPencil,
	IconPhoto,
	IconPlane,
	IconPlayerPlay,
	IconPresentation,
	IconPuzzle,
	IconRobot,
	IconRobotFace,
	IconRocket,
	IconSchool,
	IconSearch,
	IconServer,
	IconSettings,
	IconShield,
	IconShoppingCart,
	IconSparkles,
	IconStack2,
	IconStar,
	IconStars,
	IconTags,
	IconTarget,
	IconTerminal,
	IconTestPipe,
	IconTools,
	IconTrophy,
	IconVideo,
	IconWallet,
	IconWriting,
} from "@tabler/icons-react";

import { type Icon, Icons } from "@/shared/ui/icons";

// 图标分类标识（数组顺序即渲染顺序）
export const ICON_CATEGORIES = [
	{ key: "general", label: "通用" },
	{ key: "dev", label: "开发" },
	{ key: "design", label: "设计" },
	{ key: "ai", label: "AI" },
	{ key: "business", label: "商务" },
	{ key: "study", label: "学习" },
	{ key: "manage", label: "管理" },
	{ key: "life", label: "生活" },
] as const;

export type IconCategoryKey = (typeof ICON_CATEGORIES)[number]["key"];

// 单个图标选项：category 决定归属分组
type SpaceIconOption = {
	key: string;
	label: string;
	icon: Icon;
	category: IconCategoryKey;
};

// 可选图标：覆盖代码 / 设计 / AI / 商务 / 学习等常见领域
export const RULE_SPACE_ICON_OPTIONS: readonly SpaceIconOption[] = [
	// @ 通用 / 容器（保留原有 key，保证历史数据兼容）
	{ key: "rulesLibrary", label: "规约", icon: IconFolder, category: "general" },
	{ key: "star", label: "收藏", icon: IconStar, category: "general" },
	{ key: "bookmark", label: "书签", icon: IconBookmark, category: "general" },
	{ key: "tag", label: "标签", icon: IconTags, category: "general" },
	{ key: "search", label: "搜索", icon: IconSearch, category: "general" },
	{ key: "hash", label: "话题", icon: IconHash, category: "general" },
	{ key: "link", label: "链接", icon: IconLink, category: "general" },
	{ key: "clipboard", label: "剪贴板", icon: IconClipboard, category: "general" },
	{ key: "box", label: "收纳盒", icon: IconBox, category: "general" },
	{ key: "layoutGrid", label: "网格", icon: IconLayoutGrid, category: "general" },
	{ key: "settings", label: "设置", icon: IconSettings, category: "general" },
	{ key: "tools", label: "工具", icon: IconTools, category: "general" },

	// @ 开发 / 运维
	{ key: "code", label: "代码", icon: IconCode, category: "dev" },
	{ key: "terminal", label: "终端", icon: IconTerminal, category: "dev" },
	{ key: "gitBranch", label: "分支", icon: IconGitBranch, category: "dev" },
	{ key: "bug", label: "Bug", icon: IconBug, category: "dev" },
	{ key: "database", label: "数据库", icon: IconDatabase, category: "dev" },
	{ key: "server", label: "服务器", icon: IconServer, category: "dev" },
	{ key: "cloud", label: "云", icon: IconCloud, category: "dev" },
	{ key: "api", label: "API", icon: IconHierarchy, category: "dev" },
	{ key: "key", label: "密钥", icon: IconKey, category: "dev" },
	{ key: "lock", label: "锁", icon: IconLock, category: "dev" },
	{ key: "shield", label: "防护", icon: IconShield, category: "dev" },
	{ key: "certificate", label: "证书", icon: IconCertificate, category: "dev" },
	{ key: "cpu", label: "芯片", icon: IconCpu, category: "dev" },
	{ key: "deviceDesktop", label: "设备", icon: IconDeviceDesktop, category: "dev" },
	{ key: "cube", label: "模块", icon: IconCube, category: "dev" },
	{ key: "puzzle", label: "插件", icon: IconPuzzle, category: "dev" },
	{ key: "testPipe", label: "实验", icon: IconTestPipe, category: "dev" },

	// @ 设计 / 多媒体
	{ key: "palette", label: "调色板", icon: IconPalette, category: "design" },
	{ key: "pencil", label: "铅笔", icon: IconPencil, category: "design" },
	{ key: "writing", label: "写作", icon: IconWriting, category: "design" },
	{ key: "photo", label: "照片", icon: IconPhoto, category: "design" },
	{ key: "camera", label: "相机", icon: IconCamera, category: "design" },
	{ key: "video", label: "视频", icon: IconVideo, category: "design" },
	{ key: "music", label: "音乐", icon: IconMusic, category: "design" },
	{ key: "presentation", label: "演示", icon: IconPresentation, category: "design" },
	{ key: "playerPlay", label: "播放", icon: IconPlayerPlay, category: "design" },
	{ key: "brush", label: "画笔", icon: IconBrush, category: "design" },
	{ key: "colorSwatch", label: "色卡", icon: IconColorSwatch, category: "design" },
	{ key: "paletteOff", label: "配色", icon: IconPaletteOff, category: "design" },
	{ key: "movie", label: "电影", icon: IconMovie, category: "design" },
	{ key: "microphone", label: "录音", icon: IconMicrophone, category: "design" },

	// @ AI / 智能体
	{ key: "aiAgents", label: "智能体", icon: IconRobot, category: "ai" },
	{ key: "brain", label: "大脑", icon: IconBrain, category: "ai" },
	{ key: "sparkles", label: "灵感", icon: IconSparkles, category: "ai" },
	{ key: "bolt", label: "闪电", icon: IconBolt, category: "ai" },
	{ key: "atom", label: "原子", icon: IconAtom, category: "ai" },
	{ key: "hexagonLetterA", label: "AI", icon: IconHexagonLetterA, category: "ai" },
	{ key: "message", label: "对话", icon: IconMessage, category: "ai" },
	{ key: "message2", label: "聊天", icon: IconMessage2, category: "ai" },
	{ key: "robotFace", label: "面孔", icon: IconRobotFace, category: "ai" },
	{ key: "brandOpenai", label: "OpenAI", icon: IconBrandOpenai, category: "ai" },
	{ key: "binary", label: "二进制", icon: IconBinary, category: "ai" },
	{ key: "stars", label: "繁星", icon: IconStars, category: "ai" },

	// @ 商务 / 金融 / 出行
	{ key: "building", label: "公司", icon: IconBuilding, category: "business" },
	{ key: "buildingStore", label: "商店", icon: IconBuildingStore, category: "business" },
	{ key: "buildingWarehouse", label: "仓库", icon: IconBuildingWarehouse, category: "business" },
	{ key: "shoppingCart", label: "购物", icon: IconShoppingCart, category: "business" },
	{ key: "plane", label: "旅行", icon: IconPlane, category: "business" },
	{ key: "coin", label: "金币", icon: IconCoin, category: "business" },
	{ key: "wallet", label: "钱包", icon: IconWallet, category: "business" },
	{ key: "chartBar", label: "图表", icon: IconChartBar, category: "business" },
	{ key: "chartLine", label: "趋势", icon: IconChartLine, category: "business" },
	{ key: "globe", label: "全球", icon: IconGlobe, category: "business" },
	{ key: "map", label: "地图", icon: IconMap, category: "business" },

	// @ 学习 / 知识 / 成就
	{ key: "prompt", label: "笔记", icon: IconNotebook, category: "study" },
	{ key: "skills", label: "手册", icon: IconBooks, category: "study" },
	{ key: "book", label: "图书", icon: IconBook, category: "study" },
	{ key: "book2", label: "书本", icon: IconBook2, category: "study" },
	{ key: "notes", label: "便签", icon: IconNotes, category: "study" },
	{ key: "fileText", label: "文档", icon: IconFileText, category: "study" },
	{ key: "bulb", label: "灯泡", icon: IconBulb, category: "study" },
	{ key: "school", label: "学习", icon: IconSchool, category: "study" },
	{ key: "trophy", label: "奖杯", icon: IconTrophy, category: "study" },
	{ key: "award", label: "奖章", icon: IconAward, category: "study" },
	{ key: "certificate2", label: "认证", icon: IconCertificate2, category: "study" },
	{ key: "archive", label: "归档", icon: IconArchive, category: "study" },
	{ key: "stack", label: "堆叠", icon: IconStack2, category: "study" },
	{ key: "circleCheck", label: "已完成", icon: IconCircleCheck, category: "study" },
	{ key: "abc", label: "文字", icon: IconAbc, category: "study" },

	// @ 项目 / 任务 / 时间
	{ key: "projects", label: "项目", icon: IconTarget, category: "manage" },
	{ key: "flag", label: "里程碑", icon: IconFlag, category: "manage" },
	{ key: "calendar", label: "日历", icon: IconCalendar, category: "manage" },
	{ key: "clock", label: "时钟", icon: IconClock, category: "manage" },
	{ key: "listDetails", label: "清单", icon: IconListDetails, category: "manage" },
	{ key: "listCheck", label: "待办", icon: IconListCheck, category: "manage" },
	{ key: "checklist", label: "核对", icon: IconChecklist, category: "manage" },
	{ key: "clipboardList", label: "看板", icon: IconClipboardList, category: "manage" },

	// @ 生活 / 日常
	{ key: "heart", label: "喜欢", icon: IconHeart, category: "life" },
	{ key: "home", label: "主页", icon: IconHome, category: "life" },
	{ key: "coffee", label: "咖啡", icon: IconCoffee, category: "life" },
	{ key: "mug", label: "杯子", icon: IconMug, category: "life" },
	{ key: "rocket", label: "火箭", icon: IconRocket, category: "life" },
	{ key: "flame", label: "火焰", icon: IconFlame, category: "life" },
	{ key: "gift", label: "礼物", icon: IconGift, category: "life" },
	{ key: "mail", label: "邮件", icon: IconMail, category: "life" },
	{ key: "bell", label: "通知", icon: IconBell, category: "life" },
	{ key: "eye", label: "关注", icon: IconEye, category: "life" },
];

// 默认图标 key：与后端 DEFAULT_RULE_SPACE_ICON 保持一致
export const DEFAULT_SPACE_ICON_KEY = "rulesLibrary";

// > 图标 key → 图标组件；历史数据或未知 key 回落默认图标
export const resolveSpaceIcon = (key?: string): Icon =>
	RULE_SPACE_ICON_OPTIONS.find((option) => option.key === key)?.icon ?? Icons.rulesLibrary;
